"""Small Hindi pilot corpus used only when a Hindi cloud index is unavailable."""
from __future__ import annotations

HINDI_SAMPLE_DATA = [
    {
        "query_id": "hi-q1",
        "query": "ताजमहल कहाँ स्थित है?",
        "passage_id": "hi-p1",
        "passage": "ताजमहल भारत के आगरा शहर में यमुना नदी के किनारे स्थित है। इसे मुगल सम्राट शाहजहाँ ने अपनी पत्नी मुमताज महल की याद में बनवाया था।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "ताजमहल",
    },
    {
        "query_id": "hi-q2",
        "query": "भारत की राजधानी क्या है?",
        "passage_id": "hi-p2",
        "passage": "नई दिल्ली भारत की राजधानी है। यह देश की राजनीतिक और प्रशासनिक गतिविधियों का प्रमुख केंद्र है।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "नई दिल्ली",
    },
    {
        "query_id": "hi-q3",
        "query": "गंगा नदी का उद्गम कहाँ से होता है?",
        "passage_id": "hi-p3",
        "passage": "गंगा नदी का उद्गम उत्तराखंड के गंगोत्री हिमनद से होता है। वहाँ इसे भागीरथी कहा जाता है।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "गंगा नदी",
    },
    {
        "query_id": "hi-q4",
        "query": "भारत की सबसे ऊँची पर्वत चोटी कौन सी है?",
        "passage_id": "hi-p4",
        "passage": "कंचनजंगा भारत की सबसे ऊँची पर्वत चोटी है। इसकी ऊँचाई लगभग 8,586 मीटर है और यह सिक्किम में स्थित है।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "कंचनजंगा",
    },
    {
        "query_id": "hi-q5",
        "query": "भारत का संविधान कब लागू हुआ?",
        "passage_id": "hi-p5",
        "passage": "भारत का संविधान 26 जनवरी 1950 को लागू हुआ। इस दिन को भारत में गणतंत्र दिवस के रूप में मनाया जाता है।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "भारत का संविधान",
    },
    {
        "query_id": "hi-q6",
        "query": "भारत ने क्रिकेट विश्व कप कब जीता?",
        "passage_id": "hi-p6",
        "passage": "भारत ने पहली बार क्रिकेट विश्व कप 1983 में कपिल देव की कप्तानी में जीता। भारत ने दूसरी बार 2011 में विश्व कप जीता।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "क्रिकेट विश्व कप",
    },
    {
        "query_id": "hi-q7",
        "query": "महात्मा गांधी का जन्म कब हुआ था?",
        "passage_id": "hi-p7",
        "passage": "महात्मा गांधी का जन्म 2 अक्टूबर 1869 को गुजरात के पोरबंदर में हुआ था।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "महात्मा गांधी",
    },
    {
        "query_id": "hi-q8",
        "query": "भारत का राष्ट्रीय पशु कौन सा है?",
        "passage_id": "hi-p8",
        "passage": "बंगाल टाइगर भारत का राष्ट्रीय पशु है। यह अपनी शक्ति और सुंदरता के लिए जाना जाता है।",
        "language": "hi",
        "target_lang": "hin_Deva",
        "is_selected": 1,
        "title": "बंगाल टाइगर",
    },
]
