"""Embedded sample data for zero-dependency deployment on Vercel/serverless."""

EMBEDDED_SAMPLE_DATA = [
    {
        "query_id": "q1",
        "query": "Where is the Taj Mahal located?",
        "passage_id": "p1",
        "passage": "The Taj Mahal is located in the city of Agra in India, on the banks of the Yamuna River. It was built by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal. It is made of white marble and is a UNESCO World Heritage Site.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/tajmahal",
        "title": "Taj Mahal",
    },
    {
        "query_id": "q1",
        "query": "Where is the Taj Mahal located?",
        "passage_id": "p2",
        "passage": "Agra is a major city in the state of Uttar Pradesh. It is known for its historical monuments, including the Taj Mahal, Agra Fort, and Fatehpur Sikri.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/agra",
        "title": "Agra",
    },
    {
        "query_id": "q2",
        "query": "What is the capital of India?",
        "passage_id": "p3",
        "passage": "New Delhi is the capital of India. It is the center of the country's political and administrative activities and houses the Parliament House, Rashtrapati Bhavan, and the Supreme Court.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/delhi",
        "title": "New Delhi",
    },
    {
        "query_id": "q2",
        "query": "What is the capital of India?",
        "passage_id": "p4",
        "passage": "Mumbai is considered the financial capital of India. It is the capital of the state of Maharashtra and the center of the Bollywood film industry.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/mumbai",
        "title": "Mumbai",
    },
    {
        "query_id": "q3",
        "query": "Where does the Ganges river originate?",
        "passage_id": "p5",
        "passage": "The Ganges river originates from the Gangotri Glacier in Uttarakhand, where it is called the Bhagirathi. It meets the Alaknanda at Devprayag to form the Ganges and eventually empties into the Bay of Bengal.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/ganga",
        "title": "Ganga River",
    },
    {
        "query_id": "q3",
        "query": "Where does the Ganges river originate?",
        "passage_id": "p6",
        "passage": "There are many major rivers in India including the Ganges, Yamuna, Brahmaputra, Godavari, and Kaveri. These rivers are extremely important for agriculture and drinking water.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/rivers",
        "title": "Rivers of India",
    },
    {
        "query_id": "q4",
        "query": "Which is the highest mountain peak in India?",
        "passage_id": "p7",
        "passage": "Kangchenjunga is the highest mountain peak in India, with an elevation of about 8,586 meters. It is located in the state of Sikkim near the border with Nepal and is the third highest mountain in the world.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/kanchenjunga",
        "title": "Kanchenjunga",
    },
    {
        "query_id": "q4",
        "query": "Which is the highest mountain peak in India?",
        "passage_id": "p8",
        "passage": "The Himalayan mountain range spans across India, Nepal, Bhutan, and China. It is the highest mountain range in the world and includes many high peaks including Mount Everest.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/himalaya",
        "title": "Himalayas",
    },
    {
        "query_id": "q5",
        "query": "When did the Constitution of India come into effect?",
        "passage_id": "p9",
        "passage": "The Constitution of India came into effect on January 26, 1950, which is celebrated as Republic Day. It was drafted by the Drafting Committee chaired by Dr. B.R. Ambedkar.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/constitution",
        "title": "Constitution of India",
    },
    {
        "query_id": "q5",
        "query": "When did the Constitution of India come into effect?",
        "passage_id": "p10",
        "passage": "The Parliament of India has two houses: the Lok Sabha and the Rajya Sabha. Members of the Lok Sabha are directly elected by the public, while members of the Rajya Sabha are elected by the state legislative assemblies.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/parliament",
        "title": "Parliament of India",
    },
    {
        "query_id": "q6",
        "query": "When did India win the Cricket World Cup?",
        "passage_id": "p11",
        "passage": "India won the Cricket World Cup for the first time in 1983 under the captaincy of Kapil Dev. The second time India won the World Cup was in 2011 under the captaincy of Mahendra Singh Dhoni, which was hosted at home.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/worldcup",
        "title": "Cricket World Cup",
    },
    {
        "query_id": "q6",
        "query": "When did India win the Cricket World Cup?",
        "passage_id": "p12",
        "passage": "Cricket is the most popular sport in India. The Indian Premier League (IPL) is a major Twenty20 cricket league that started in 2008.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/ipl",
        "title": "IPL",
    },
    {
        "query_id": "q7",
        "query": "When was Mahatma Gandhi born?",
        "passage_id": "p13",
        "passage": "Mahatma Gandhi was born on October 2, 1869, in Porbandar, Gujarat. He used the principles of non-violence and Satyagraha in India's freedom struggle.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/gandhi",
        "title": "Mahatma Gandhi",
    },
    {
        "query_id": "q7",
        "query": "When was Mahatma Gandhi born?",
        "passage_id": "p14",
        "passage": "India gained independence from British rule on August 15, 1947. Jawaharlal Nehru became the first Prime Minister of India.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/independence",
        "title": "Indian Independence",
    },
    {
        "query_id": "q8",
        "query": "Which is the national animal of India?",
        "passage_id": "p15",
        "passage": "The Bengal Tiger is the national animal of India. It is known for its strength and beauty, and the Government of India launched Project Tiger in 1973 for its conservation.",
        "language": "en",
        "is_selected": 1,
        "url": "https://example.org/tiger",
        "title": "Bengal Tiger",
    },
    {
        "query_id": "q8",
        "query": "Which is the national animal of India?",
        "passage_id": "p16",
        "passage": "The national bird of India is the peacock and the national flower is the lotus. The mango is considered the national fruit of India.",
        "language": "en",
        "is_selected": 0,
        "url": "https://example.org/symbols",
        "title": "National Symbols",
    },
]
